from reportlab.platypus import (
SimpleDocTemplate,
Paragraph,
Spacer,
PageBreak
)

from reportlab.lib.styles import (
getSampleStyleSheet
)

import os

def generate_pdf(report, user_id):


# Create reports folder if missing

 os.makedirs(
    "reports",
    exist_ok=True
)

pdf_path = (
    f"reports/report_{user_id}.pdf"
)

pdf = SimpleDocTemplate(
    pdf_path
)

styles = getSampleStyleSheet()

elements = []

# ==========================
# Title
# ==========================

elements.append(
    Paragraph(
        "Plagiarism Detection Report",
        styles["Title"]
    )
)

elements.append(
    Spacer(1, 20)
)

# ==========================
# Report Information
# ==========================

for key, value in report.items():

    elements.append(
        Paragraph(
            f"<b>{key}</b>: {value}",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 8)
    )

elements.append(
    Spacer(1, 20)
)

elements.append(
    Paragraph(
        "Generated by Plagiarism Detector System",
        styles["Italic"]
    )
)

pdf.build(
    elements
)

return pdf_path
```
